// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package peer

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AnchorPeers simply represents list of anchor peers which is used in ConfigurationItem
type AnchorPeers struct {
	AnchorPeers          []*AnchorPeer `protobuf:"bytes,1,rep,name=anchor_peers,json=anchorPeers,proto3" json:"anchor_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnchorPeers) Reset()         { *m = AnchorPeers{} }
func (m *AnchorPeers) String() string { return proto.CompactTextString(m) }
func (*AnchorPeers) ProtoMessage()    {}
func (*AnchorPeers) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *AnchorPeers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorPeers.Unmarshal(m, b)
}
func (m *AnchorPeers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorPeers.Marshal(b, m, deterministic)
}
func (m *AnchorPeers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorPeers.Merge(m, src)
}
func (m *AnchorPeers) XXX_Size() int {
	return xxx_messageInfo_AnchorPeers.Size(m)
}
func (m *AnchorPeers) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorPeers.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorPeers proto.InternalMessageInfo

func (m *AnchorPeers) GetAnchorPeers() []*AnchorPeer {
	if m != nil {
		return m.AnchorPeers
	}
	return nil
}

// AnchorPeer message structure which provides information about anchor peer, it includes host name,
// port number and peer certificate.
type AnchorPeer struct {
	// DNS host name of the anchor peer
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// The port number
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnchorPeer) Reset()         { *m = AnchorPeer{} }
func (m *AnchorPeer) String() string { return proto.CompactTextString(m) }
func (*AnchorPeer) ProtoMessage()    {}
func (*AnchorPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *AnchorPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorPeer.Unmarshal(m, b)
}
func (m *AnchorPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorPeer.Marshal(b, m, deterministic)
}
func (m *AnchorPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorPeer.Merge(m, src)
}
func (m *AnchorPeer) XXX_Size() int {
	return xxx_messageInfo_AnchorPeer.Size(m)
}
func (m *AnchorPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorPeer.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorPeer proto.InternalMessageInfo

func (m *AnchorPeer) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AnchorPeer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// Endorsers simply represents list of endorsing peers which is used in ConfigurationItem
type Endorsers struct {
	Endorsers            []*Endorser `protobuf:"bytes,1,rep,name=endorsers,proto3" json:"endorsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Endorsers) Reset()         { *m = Endorsers{} }
func (m *Endorsers) String() string { return proto.CompactTextString(m) }
func (*Endorsers) ProtoMessage()    {}
func (*Endorsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{2}
}

func (m *Endorsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endorsers.Unmarshal(m, b)
}
func (m *Endorsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endorsers.Marshal(b, m, deterministic)
}
func (m *Endorsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorsers.Merge(m, src)
}
func (m *Endorsers) XXX_Size() int {
	return xxx_messageInfo_Endorsers.Size(m)
}
func (m *Endorsers) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorsers.DiscardUnknown(m)
}

var xxx_messageInfo_Endorsers proto.InternalMessageInfo

func (m *Endorsers) GetEndorsers() []*Endorser {
	if m != nil {
		return m.Endorsers
	}
	return nil
}

// Endorser message structure which provides information about endorser, it includes host address.
type Endorser struct {
	// DNS host name of the endorser
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endorser) Reset()         { *m = Endorser{} }
func (m *Endorser) String() string { return proto.CompactTextString(m) }
func (*Endorser) ProtoMessage()    {}
func (*Endorser) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{3}
}

func (m *Endorser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endorser.Unmarshal(m, b)
}
func (m *Endorser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endorser.Marshal(b, m, deterministic)
}
func (m *Endorser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorser.Merge(m, src)
}
func (m *Endorser) XXX_Size() int {
	return xxx_messageInfo_Endorser.Size(m)
}
func (m *Endorser) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorser.DiscardUnknown(m)
}

var xxx_messageInfo_Endorser proto.InternalMessageInfo

func (m *Endorser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// APIResource represents an API resource in the peer whose ACL
// is determined by the policy_ref field
type APIResource struct {
	PolicyRef            string   `protobuf:"bytes,1,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIResource) Reset()         { *m = APIResource{} }
func (m *APIResource) String() string { return proto.CompactTextString(m) }
func (*APIResource) ProtoMessage()    {}
func (*APIResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{4}
}

func (m *APIResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResource.Unmarshal(m, b)
}
func (m *APIResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResource.Marshal(b, m, deterministic)
}
func (m *APIResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResource.Merge(m, src)
}
func (m *APIResource) XXX_Size() int {
	return xxx_messageInfo_APIResource.Size(m)
}
func (m *APIResource) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResource.DiscardUnknown(m)
}

var xxx_messageInfo_APIResource proto.InternalMessageInfo

func (m *APIResource) GetPolicyRef() string {
	if m != nil {
		return m.PolicyRef
	}
	return ""
}

// ACLs provides mappings for resources in a channel. APIResource encapsulates
// reference to a policy used to determine ACL for the resource
type ACLs struct {
	Acls                 map[string]*APIResource `protobuf:"bytes,1,rep,name=acls,proto3" json:"acls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ACLs) Reset()         { *m = ACLs{} }
func (m *ACLs) String() string { return proto.CompactTextString(m) }
func (*ACLs) ProtoMessage()    {}
func (*ACLs) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{5}
}

func (m *ACLs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACLs.Unmarshal(m, b)
}
func (m *ACLs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACLs.Marshal(b, m, deterministic)
}
func (m *ACLs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACLs.Merge(m, src)
}
func (m *ACLs) XXX_Size() int {
	return xxx_messageInfo_ACLs.Size(m)
}
func (m *ACLs) XXX_DiscardUnknown() {
	xxx_messageInfo_ACLs.DiscardUnknown(m)
}

var xxx_messageInfo_ACLs proto.InternalMessageInfo

func (m *ACLs) GetAcls() map[string]*APIResource {
	if m != nil {
		return m.Acls
	}
	return nil
}

func init() {
	proto.RegisterType((*AnchorPeers)(nil), "protos.AnchorPeers")
	proto.RegisterType((*AnchorPeer)(nil), "protos.AnchorPeer")
	proto.RegisterType((*Endorsers)(nil), "protos.Endorsers")
	proto.RegisterType((*Endorser)(nil), "protos.Endorser")
	proto.RegisterType((*APIResource)(nil), "protos.APIResource")
	proto.RegisterType((*ACLs)(nil), "protos.ACLs")
	proto.RegisterMapType((map[string]*APIResource)(nil), "protos.ACLs.AclsEntry")
}

func init() { proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab) }

var fileDescriptor_415c9e57263f32ab = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcd, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0x3f, 0xde, 0xd7, 0x4c, 0x3c, 0x94, 0x2d, 0x48, 0x10, 0x84, 0x12, 0x3c, 0xb4,
	0x22, 0x1b, 0xa8, 0x0a, 0xa2, 0xa7, 0x58, 0x7b, 0x10, 0x0a, 0x96, 0x3d, 0x7a, 0x29, 0xdb, 0xcd,
	0xe6, 0x03, 0x63, 0x36, 0xcc, 0x26, 0x42, 0x6e, 0xfe, 0xe9, 0x92, 0x8f, 0x6d, 0x3c, 0x65, 0x9e,
	0x27, 0xbf, 0xd9, 0x67, 0x86, 0x81, 0xb9, 0x50, 0x79, 0x94, 0xc6, 0x15, 0xf2, 0x32, 0x55, 0x39,
	0x2d, 0x50, 0x95, 0x8a, 0xfc, 0x6b, 0x3f, 0xda, 0x7b, 0x05, 0x27, 0xc8, 0x45, 0xa2, 0x70, 0x2f,
	0x25, 0x6a, 0xf2, 0x00, 0xe7, 0xbc, 0x95, 0x87, 0xa2, 0xd1, 0xae, 0xb5, 0x18, 0x2f, 0x9d, 0x35,
	0xe9, 0x9a, 0x34, 0x1d, 0x50, 0xe6, 0xf0, 0xa1, 0xcd, 0xbb, 0x07, 0x18, 0x7e, 0x11, 0x02, 0x93,
	0x44, 0xe9, 0xd2, 0xb5, 0x16, 0xd6, 0xd2, 0x66, 0x6d, 0xdd, 0x78, 0x85, 0xc2, 0xd2, 0x1d, 0x2d,
	0xac, 0xe5, 0x94, 0xb5, 0xb5, 0xf7, 0x0c, 0xf6, 0x36, 0x0f, 0x15, 0xea, 0x26, 0x99, 0x82, 0x2d,
	0x8d, 0xe8, 0x63, 0x67, 0x26, 0xd6, 0x50, 0x6c, 0x40, 0xbc, 0x6b, 0x38, 0x33, 0x36, 0x71, 0xe1,
	0x3f, 0x0f, 0x43, 0x94, 0x5a, 0xf7, 0x99, 0x46, 0x7a, 0xb7, 0xe0, 0x04, 0xfb, 0x37, 0x26, 0xb5,
	0xaa, 0x50, 0x48, 0x72, 0x05, 0x50, 0xa8, 0x2c, 0x15, 0xf5, 0x01, 0x65, 0xd4, 0xb3, 0x76, 0xe7,
	0x30, 0x19, 0x79, 0x3f, 0x16, 0x4c, 0x82, 0xcd, 0x4e, 0x93, 0x1b, 0x98, 0x70, 0x91, 0x99, 0x39,
	0x2e, 0x4e, 0xeb, 0x6f, 0x76, 0x9a, 0x06, 0x22, 0xd3, 0xdb, 0xbc, 0xc4, 0x9a, 0xb5, 0xcc, 0xe5,
	0x0e, 0xec, 0x93, 0x45, 0x66, 0x30, 0xfe, 0x94, 0x75, 0xff, 0x72, 0x53, 0x92, 0x15, 0x4c, 0xbf,
	0x79, 0x56, 0xc9, 0x76, 0x73, 0x67, 0x3d, 0x3f, 0xbd, 0x35, 0x8c, 0xc5, 0x3a, 0xe2, 0x69, 0xf4,
	0x68, 0xbd, 0xbc, 0x83, 0xa7, 0x30, 0xa6, 0x49, 0x5d, 0x48, 0xcc, 0x64, 0x18, 0x4b, 0xa4, 0x11,
	0x3f, 0x62, 0x2a, 0x4c, 0x5f, 0x73, 0x97, 0x8f, 0x55, 0x9c, 0x96, 0x49, 0x75, 0xa4, 0x42, 0x7d,
	0xf9, 0x7f, 0x50, 0xbf, 0x43, 0xfd, 0x0e, 0xf5, 0x1b, 0xf4, 0xd8, 0x1d, 0xfa, 0xee, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0xd8, 0x04, 0x88, 0x06, 0x02, 0x00, 0x00,
}
